using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StorageLabelsApi.DataLayer.Models;

/// <summary>
/// Supported physical label formats
/// </summary>
public enum LabelFormat
{
    /// <summary>
    /// Avery 94107 - 2" x 2", 12 per page (3 columns x 4 rows)
    /// </summary>
    Avery94107
}

/// <summary>
/// Algorithm used to increment label codes when generating pages
/// </summary>
public enum LabelIncrementAlgorithm
{
    /// <summary>
    /// Suffix is a zero-padded decimal number (0000, 0001, ..., 9999)
    /// </summary>
    NumericOnly,

    /// <summary>
    /// Suffix is a base-36 value using digits 0-9 then A-Z (e.g. 0000, ..., 000Z, 0010, ...)
    /// </summary>
    Base36Suffix
}

/// <summary>
/// Represents a saved label print job configuration
/// </summary>
[Table("labelprintjobs")]
public class LabelPrintJob
{
    /// <summary>
    /// Unique identifier for the print job
    /// </summary>
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Friendly name for this job configuration
    /// </summary>
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Physical label sheet format to print on
    /// </summary>
    public LabelFormat LabelFormat { get; set; } = LabelFormat.Avery94107;

    /// <summary>
    /// Algorithm used to generate the incremented code suffix
    /// </summary>
    public LabelIncrementAlgorithm IncrementAlgorithm { get; set; } = LabelIncrementAlgorithm.NumericOnly;

    /// <summary>
    /// Optional static prefix prepended before the suffix (e.g. "A75ACC")
    /// </summary>
    [MaxLength(50)]
    public string? AlgorithmPrefix { get; set; }

    /// <summary>
    /// Number of characters in the suffix portion of each code
    /// </summary>
    public int AlgorithmSuffixLength { get; set; } = 4;

    /// <summary>
    /// The index of the last generated batch (incremented by labels-per-page each print)
    /// </summary>
    public long LastGeneratedIndex { get; set; } = 0;

    /// <summary>
    /// Total number of labels ever generated by this job
    /// </summary>
    public int TotalLabelsGenerated { get; set; } = 0;

    /// <summary>
    /// Code color pattern string used to format codes on labels (e.g. "3:primary,4:warning,*")
    /// </summary>
    [MaxLength(200)]
    public string CodeColorPattern { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp when this job was created
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// Identity user ID of the user who created this job
    /// </summary>
    [MaxLength(450)]
    public string CreatedBy { get; set; } = string.Empty;
}
