// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StorageLabelsApi.Datalayer;

#nullable disable

namespace StorageLabelsApi.Migrations
{
    [DbContext(typeof(StorageLabelsDbContext))]
    [Migration("20251116023848_InitialPostgreSQL")]
    partial class InitialPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Box", b =>
                {
                    b.Property<Guid>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageMetadataId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImageMetadataId");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAccessed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BoxId");

                    b.HasIndex("Code");

                    b.HasIndex("ImageMetadataId");

                    b.HasIndex("LocationId", "Code")
                        .IsUnique();

                    b.ToTable("boxes", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.CommonLocation", b =>
                {
                    b.Property<int>("CommonLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommonLocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommonLocationId");

                    b.ToTable("commonlocations", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.ImageMetadata", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageMetadataId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImageMetadataId");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("BoxId");

                    b.HasIndex("ImageMetadataId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LocationId"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Preferences")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.UserLocation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("userlocations", (string)null);
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Box", b =>
                {
                    b.HasOne("StorageLabelsApi.DataLayer.Models.ImageMetadata", "ImageMetadata")
                        .WithMany("ReferencedByBoxes")
                        .HasForeignKey("ImageMetadataId");

                    b.HasOne("StorageLabelsApi.DataLayer.Models.Location", "Location")
                        .WithMany("Boxes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageMetadata");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Item", b =>
                {
                    b.HasOne("StorageLabelsApi.DataLayer.Models.Box", "Box")
                        .WithMany("Items")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorageLabelsApi.DataLayer.Models.ImageMetadata", "ImageMetadata")
                        .WithMany("ReferencedByItems")
                        .HasForeignKey("ImageMetadataId");

                    b.Navigation("Box");

                    b.Navigation("ImageMetadata");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.UserLocation", b =>
                {
                    b.HasOne("StorageLabelsApi.DataLayer.Models.Location", "Location")
                        .WithMany("UserLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StorageLabelsApi.DataLayer.Models.User", "User")
                        .WithMany("UserLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Box", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.ImageMetadata", b =>
                {
                    b.Navigation("ReferencedByBoxes");

                    b.Navigation("ReferencedByItems");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.Location", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("UserLocations");
                });

            modelBuilder.Entity("StorageLabelsApi.DataLayer.Models.User", b =>
                {
                    b.Navigation("UserLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
