services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: msslq
    environment:
      - MSSQL_PID=Express
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/mssql
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
    restart: unless-stopped
volumes:
  db_data: